language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node_modules"
install:
  - npm install
script:
  - npm run build
  - npm run test:e2e
  - npm run test:unit
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: build
  on:
    branch: master
